In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

In [3]:
import sklearn as sk

In [4]:
sk.__version__

'0.21.3'

In [5]:
from sklearn import preprocessing

In [6]:
ll = [-500.5, -100.1, 0, 100.1, 900.9]

In [7]:
ll = np.array(ll)

In [8]:
ll = ll.reshape(-1,1)

In [9]:
ll

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [10]:
feature = ll.copy()

In [11]:
std_scaler = preprocessing.StandardScaler()

In [12]:
std_scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

## fit_transform으로 처리하기

In [13]:
scaled_feature = std_scaler.fit_transform(feature)

In [14]:
scaled_feature

array([[-1.26687088],
       [-0.39316683],
       [-0.17474081],
       [ 0.0436852 ],
       [ 1.79109332]])

## 표준점수 처리

    평균을 빼고 표준편차로 나눠서 구함

In [15]:
a = np.std(feature)

In [16]:
b = np.mean(feature)

In [17]:
def standard(a,b, x) :
    return (x -b)/a

In [18]:
standard(a,b,feature)

array([[-1.26687088],
       [-0.39316683],
       [-0.17474081],
       [ 0.0436852 ],
       [ 1.79109332]])

## fit, transform 으로 처리하기

In [19]:
a_mm = std_scaler.fit(feature)

In [20]:
a_mm.transform(feature)

array([[-1.26687088],
       [-0.39316683],
       [-0.17474081],
       [ 0.0436852 ],
       [ 1.79109332]])

## 훈련세트와 테스트 세트는 동일한 기준으로 처리

###  따로 처리하면 기준점이 차이가 생김

In [21]:
preprocessing.StandardScaler().fit_transform(feature[:3])

array([[-1.38873015],
       [ 0.46291005],
       [ 0.9258201 ]])

In [22]:
preprocessing.StandardScaler().fit_transform(feature[3:])

array([[-1.],
       [ 1.]])

### 훈련 데이터 기준으로 만들기 위해서는 먼저 fit 후에 적용

In [23]:
scaler = preprocessing.StandardScaler().fit(feature[:3])

In [24]:
scaler.transform(feature[:3])

array([[-1.38873015],
       [ 0.46291005],
       [ 0.9258201 ]])

In [25]:
scaler.transform(feature[3:])

array([[1.38873015],
       [5.09201055]])

## 데이터에 이상치가 많은 경우 평균과 표준편차에 영향을 미침

    중앙값과 사분위 범위를 사용한 스케일러 처리가 필요

In [26]:
robust = preprocessing.RobustScaler()

In [27]:
robust.fit_transform(feature)

array([[-2.5],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 4.5]])

In [28]:
interquantile = np.quantile(feature,[0.75, 0.25])

In [29]:
interquantile

array([ 100.1, -100.1])

In [30]:
feature

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [31]:
(feature - np.median(feature)) / (interquantile[0] - interquantile[1])

array([[-2.5],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 4.5]])

### 더 세분화된 데이터로 만들어서 계산하기

In [32]:
feature.shape

(5, 1)

In [33]:
preprocessing.QuantileTransformer(n_quantiles=5).fit_transform(feature)

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [34]:
X = np.sort(np.random.normal(loc=0.5, scale=0.25, size=(25, 1)), axis=0)

In [35]:
X.shape

(25, 1)

In [36]:
qt = preprocessing.QuantileTransformer(n_quantiles=10, random_state=0)
cc = qt.fit_transform(X) 

In [37]:
cc.shape

(25, 1)

In [38]:
cc

array([[0.        ],
       [0.08026765],
       [0.10768408],
       [0.12334445],
       [0.14069164],
       [0.21220681],
       [0.23472838],
       [0.23618827],
       [0.33333333],
       [0.41556148],
       [0.42568671],
       [0.46219363],
       [0.48208112],
       [0.48464306],
       [0.58853563],
       [0.61606445],
       [0.66666667],
       [0.67195493],
       [0.74081353],
       [0.78866911],
       [0.79798412],
       [0.87268546],
       [0.92184753],
       [0.97603921],
       [1.        ]])