In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

In [3]:
import sklearn as sk

In [4]:
sk.__version__

'0.21.3'

In [5]:
from sklearn import preprocessing

In [6]:
ll = [-500.5, -100.1, 0, 100.1, 900.9]

In [7]:
ll = np.array(ll)

In [8]:
ll = ll.reshape(-1,1)

In [9]:
ll

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [10]:
feature = ll.copy()

In [11]:
norm_scaler = preprocessing.Normalizer()

In [12]:
norm_scaler

Normalizer(copy=True, norm='l2')

## fit_transform으로 처리하기

In [13]:
scaled_feature = norm_scaler.fit_transform(feature)

In [14]:
scaled_feature

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

## Norm으로 처리하기

    노름으로 처리하기

In [15]:
a = np.linalg.norm(feature[0])

In [16]:
a

500.5

In [17]:
if np.nan :
    print('xxxx')
else :
    print('yyyy')

xxxx


In [18]:
def normal( x) :
    result = []
    for i in x :
        if  np.isnan((i/np.linalg.norm(i))[0])  :
            result.append(0)
        else : 
            result.append(((i/np.linalg.norm(i))[0]))
    return result

In [19]:
normal(feature)

/Users/dahlmoon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


[-1.0, -1.0, 0, 1.0, 1.0]

## fit, transform 으로 처리하기

In [20]:
a_mm = norm_scaler.fit(feature)

In [21]:
a_mm.transform(feature)

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

## 훈련세트와 테스트 세트는 동일한 기준으로 처리

###  따로 처리하면 기준점이 차이가 생김

In [22]:
preprocessing.Normalizer().fit_transform(feature[:3])

array([[-1.],
       [-1.],
       [ 0.]])

In [23]:
preprocessing.Normalizer().fit_transform(feature[3:])

array([[1.],
       [1.]])

### 훈련 데이터 기준으로 만들기 위해서는 먼저 fit 후에 적용

In [24]:
scaler = preprocessing.Normalizer().fit(feature[:3])

In [25]:
scaler.transform(feature[:3])

array([[-1.],
       [-1.],
       [ 0.]])

In [26]:
scaler.transform(feature[3:])

array([[1.],
       [1.]])