In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

In [3]:
import sklearn as sk

In [4]:
sk.__version__

'0.21.3'

In [5]:
from sklearn import preprocessing

In [6]:
ll = [-500.5, -100.1, 0, 100.1, 900.9]

In [7]:
ll = np.array(ll)

In [8]:
ll = ll.reshape(-1,1)

In [9]:
ll

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [10]:
feature = ll.copy()

In [12]:
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))

In [13]:
minmax

MinMaxScaler(copy=True, feature_range=(0, 1))

## fit_transform으로 처리하기

In [14]:
scaled_feature = minmax.fit_transform(feature)

In [15]:
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [18]:
a = np.max(feature)

In [19]:
b = np.min(feature)

In [20]:
def min_max(a,b, x) :
    return (x -b)/(a-b)

In [21]:
min_max(a,b,feature)

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## fit, transform 으로 처리하기

In [23]:
a_mm = minmax.fit(feature)

In [24]:
a_mm.transform(feature)

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## 훈련세트와 테스트 세트는 동일한 기준으로 처리

###  따로 처리하면 기준점이 차이가 생김

In [26]:
preprocessing.MinMaxScaler().fit_transform(feature[:3])

array([[0. ],
       [0.8],
       [1. ]])

In [27]:
preprocessing.MinMaxScaler().fit_transform(feature[3:])

array([[0.],
       [1.]])

### 훈련 데이터 기준으로 만들기 위해서는 먼저 fit 후에 적용

In [28]:
scaler = preprocessing.MinMaxScaler().fit(feature[:3])

In [30]:
scaler.transform(feature[:3])

array([[0. ],
       [0.8],
       [1. ]])

In [31]:
scaler.transform(feature[3:])

array([[1.2],
       [2.8]])